name: Docker

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run test in docker container
        env:
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
        run: |
          echo 'run unit test'
          docker-compose up --exit-code-from test test

  build_image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: docker build
        run: docker build . -t tradingai/tenvs:latest

      - name: docker push-logout
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push tradingai/tenvs:latest
          docker image tag tradingai/tenvs:1.0.9 tradingai/tenvs:latest
          docker push tradingai/tenvs:1.0.9
          docker logout
