name: Docker

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run test in docker container
        env:
          BAZEL_USER_ROOT: /home/runner/BAZEL_USER_ROOT
          OUTPUT_DIR: /home/runner/OUTPUT_DIR
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
        run: |
          sudo mkdir -p $BAZEL_USER_ROOT
          sudo mkdir -p $OUTPUT_DIR
          docker-compose up --exit-code-from test test

  build_image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: docker build
        run: docker build . -t tradingai/bazel:latest

      - name: docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: docker push-logout
        run: |
          docker push tradingai/tenvs:latest
          docker logout
