name: Dev Test

on:
  push:
    branches: [main, dev]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9.2]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v2
        id: pip_cache
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Unit Test
        env:
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
        run: |
          python -c "import sys; print('Python', sys.version)"
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .
          python -m pytest --cov-report=xml --cov=tenvs --cov-config=.coveragerc
          coverage report -m

      - name: Lint with flake8
        # pip install flake8
        run: |
          flake8 .

      - name: Upload to codecov
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: docs/cov/report.xml

  platforms:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: [3.8, 3.9.2]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Unit Test
        env:
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
        run: |
          python -c "import sys; print('Python', sys.version)"
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .
          python -m pytest --cov-report=xml --cov=tenvs --cov-config=.coveragerc
          coverage report -m

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests in docker container
        env:
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
        run: |
          echo "Unit test"
          docker-compose up --exit-code-from test test
